### PR TITLE
Three cities debiasing

### LINKED ISSUE #46: Choose standard method for preprocessing
Unify current R and python preprocessing pipelines

We want to have a common pipeline that consists of:
- All existing steps (downloading, resampling, reprojection) in Python and bash.
- Cropping based on three cities geometries in R as described in #34 and implemented in #44 
- Grouping of files into calibration/validation/testing periods in Python. This will come from splitting the python debiasing script (`python/debiasing/run_cmethods.py`) into a grouping step and a debiasing step. The grouping step will take all input files and produce output files that are grouped into the requested time frames. The debiasing code will just run the debiasing algorithms.

- [x] push pipeline viz on repo
- [x] Merge #44 
- [ ] Merge #47

### PR DESCRIPTION
**Pull request by gmingas**
Closes #46 

This PR adds the following:
- Splits the `run_cmethods.py` script into two scripts (`preprocess_data.py` and `run_cmethods.py`). 
  - The `preprocess_data.py` script does all the data loading (with new arguments to specify calibration and validation dates), and combines input CPM and HADs files into the following four output files:
    - `modc.nc`: Modelled (CPM) data for calibration period
    - `obsc.nc`: Observed (HADs) data for calibration period
    - `modv.nc`: Modelled (CPM) data for validation period
    - `obsv.nc`: Observed (HADs) data for validation period
The script allows multiple validation periods to be passed, in which case multiple sets of validation files are generated. 
  - The `run_cmethods.py` script reads the above files and applies debiasing using cmethods. 
- Bash script to run all for all the cropped data in Azure (`three_cities_debiasing_cropped.sh`).
- Updates readme file for the python scripts.

<s>This PR might not need to be merged to main. It is temporary to allow us to workaround the issues with 360-day calendars (#32) and test the python debiasing pipeline. It adds:
- Temporary script to convert Hads observation data (.tif) generated by Ruth's R script in #44 to 360-day-per-year format. The script also modifies the names of the Hads files in the output to match the naming format in the Azure `Processed/HadsUKgrid/resampled_2.2km` folder and saves them in `.nc` format (same as the original Hads format in `Processed/HadsUKgrid/resampled_2.2km`). The script only processes the `rainfall` and `tasmax` files (tasmin is going to be added later due to some differences in dates included in the files).
</s>

### CODE REVIEW

**Comment by aranas** [comment]
I have made some suggestions (see previous comments) that I think are necessary to better share and showcase the full pipeline when it comes to documentation and potential jupyter notebooks we want to include.

In addition, I would suggest to keep the input parameter names coherent with the variable names, at the moment we mix multiple terms and this is a bit confusing:

control = simulation historic (simh)
scenario = simulation projection (simp)
observation = observation historic (obsh)

control_dates = calibration_dates
senario_dates = projection_dates

**Comment by RuthBowyer** [comment]
I agree, I also find it a bit confusing! To me the word 'projection' = a time period in the future, so I would favour:

calibration for control/simulation historic (a simulation can't be a control imo)
validation for scenario/simulation projection (because sim projection would in my brain include the dates past 2020, and scenario also refers to the 'climate scenario'
observatio/observation historic is grand with me

And then we use projection to mean 2020 onwards? 

Happy to go with whatever you guys prefer though!

**Review by aranas — COMMENTED** [review]
Here are my comments, it's mainly to do with moving some code into modules for better display in sphinx documentation ToC. 
Since today we decided the code base documentation would come later, this might not be very urgent right now. I could move my suggestions into this issue instead #56  so that merging of this PR does not get blocked. @gmingas I leave it up to you to decide if and when these comments should be addressed.

**Comment by gmingas** [comment]
@aranas @RuthBowyer I think this is ready for review now. It seems the code works for both the original and updated Hads cropped inputs (but some updated files are missing as discussed).

I think it is better to address Sophie's comments in a separate issue/PR.

**Comment by gmingas** [comment]
@RuthBowyer @aranas Quick update, it seems all Hads files are now in place and this is running as expected, happy to merge the PR as soon as you approve.

**Comment by aranas** [comment]
I have transferred my remaining comments into a new issue (for future reference)

**Review by aranas — APPROVED** [review]
Looks good to me!

**Pull request merged**
