### PR TITLE
Data processing r

### PR DESCRIPTION
**Pull request by RuthBowyer**

### CODE REVIEW

**Review by gmingas — COMMENTED** [review]
Hi Ruth, I have been working with the raster data you produced with this code, a couple of things I noticed:
- The clim-recal code needs specific naming for the input files, with the dates at the end of the file name in the format `_19800101-20091230.tif`, rather than `_1980_2010.tif`. Applies to both CPM and HADS.
- For HADS data, the code apparently does not work with `.tif` data, only `.nc`. I think I can fix this but is it easier to just modify the R code to generate `.nc` for observational data?

**Comment by RuthBowyer** [comment]
Thanks Greg! 

> The clim-recal code needs specific naming for the input files, with the dates at the end of the file name in the format _19800101-20091230.tif, rather than _1980_2010.tif. Applies to both CPM and HADS.

I'm sorry I'm not sure which part of the code are you referring to? Thank you!

**Comment by aranas** [comment]
Hi @gmingas 
>     Correction: I think the reason it fails is that the time index in the xarray is misaligned with the number of dates in the date range (maybe because of [HADs 360 day calendar conversion #32](https://github.com/alan-turing-institute/clim-recal/issues/32) ). Maybe this can be fixed by adapting the date range constructed within the clim recal code (?)

which code are we talking about here the [WIP_MBC.Rmd](https://github.com/alan-turing-institute/clim-recal/pull/44/commits/e645beb69956ba78355b77c9fcec856d14009c97) script?
And which date range are you referring to?

**Comment by RuthBowyer** [comment]
So sorry for this oversight:

> Unfortunately I get some errors because the functions vect and ext

I should have called the library `terra` - I've just added this into the script 

> either in R or python that will be compatible with all the debiasing methods. 

I think there might always be additional/different steps as the input to all (so far) of the BC methods I have used in R is a data.frame, and some need to be transposed others pivoted to long format, but completely agree it would be great to have as near to similar input as possible.

>The Hads files generated by the new scripts in this PR are in .tif format (not .nc which is used for the original Hads data). Not sure if this is intentional but might be easier to maintain the same format in the final pipeline?

Yes it was intentional because .nc I believe (but couldbe wrong) takes longer to write and .tif is easier to work with/smaller, but happy to switch to .nc. For the LCAT data I will remain with .tif however as I know they prefer this format

**Review by aranas — APPROVED** [review]

**Pull request merged**
