### PR TITLE
Remove debiasing folder

### PR DESCRIPTION
**Pull request by andrewphilipsmith**

### CODE REVIEW

**Review by RuthBowyer — APPROVED** [review]

**Comment by andrewphilipsmith** [comment]
Still todo; update `docs/contributing.md`

**Comment by andrewphilipsmith** [comment]
Question for @RuthBowyer do we want to keep any of these files?:

* `docs/deprecated_pipeline.qmd`
* `notebooks/Assessing_bc_data/MethodsAssessment_DecWorkshop.Rmd`
* `notebooks/Assessing_bc_data/Bias correction assessment.html`

**Comment by andrewphilipsmith** [comment]
@sgreenbury Please could you have a quick look at the updated `contributing.md` doc?

**Comment by sgreenbury** [comment]
> @sgreenbury Please could you have a quick look at the updated `contributing.md` doc?

The updated `contributing.md` looks good to me, thanks @andrewphilipsmith. I added one suggestion above in the docs in case useful.

**Comment by andrewphilipsmith** [comment]
> Question for @RuthBowyer do we want to keep any of these files?:
> 
> * `docs/deprecated_pipeline.qmd`
> * `notebooks/Assessing_bc_data/MethodsAssessment_DecWorkshop.Rmd`
> * `notebooks/Assessing_bc_data/Bias correction assessment.html`

This was discussed offline. These files have been removed.

**Pull request merged**
