### PR TITLE
Lcat.data

### PR DESCRIPTION
**Pull request by RuthBowyer**
Hey @gmingas and @aranas  - I'm going through the steps to better seperate out older code used for the LCAT data (which probably won't be re-run anytime soon) and then I'll update the R pipeline in another branch. 
So much of this code will end up just being used in the LCAT processing and I will use a cleaned up version for the three cities processing! 
Hope it makes sense!

### CODE REVIEW

**Comment by griff-rees** [comment]
@RuthBowyer if I remember correctly this is pretty crucial to merge in prep for December. Maybe this is the place to start? Note to myself on managing the necessary dependencies: https://github.com/rstudio/renv/issues/946

**Comment by RuthBowyer** [comment]
Hey there - it would be great to merge this (I note the conflicts which I will resolve!) - but this branch *should* relate to the work done to process the data for LCAT; for the 'three cities' pipeline I ran a slightly more general (but probably not helpfully general enough) version of the pipeline. I will add this to my list this week to sort out as I agree it needs to be sorted before December! 
It does give me a thought though @dingaaling - should we invite the new LCAT data folks to the workshop?

**Comment by andrewphilipsmith** [comment]
Just looking at the merge conflict for `R/misc/read_crop.fn.R`. They both add in two similar functions:
* `main` branch ==> `hads_read_crop_df`
* `LCAT.data` branch ==> `hads_read_crop2`

Given that they don't appear to conflict functionally, I suggest that we add in both functions and then open an issue to work out which we should keep.

@RuthBowyer could you make a call on this please?

**Comment by andrewphilipsmith** [comment]
@RuthBowyer Assigning this to you. Since merging #122, it is not clear (to @griff-rees and me) whether or not there is anything in this PR that needs to be preserved and isn't already included in #122.

**Comment by RuthBowyer** [comment]
Hey @andrewphilipsmith @griff-rees 

Sorry again for this! I think all is well, but I believe there are some files which are on the LCAT branch which are deleted on main - I'm sure all of which are my fault/I probably deleted them on the other branch, apologies. 

They are all on the LCAT branch in `R/misc` and relate to converting data from rasters to data frames to make R processing easier 

To explain why (I think) these issues arose, it's because we have since updated the pipelines and processing, but I was trying to keep a record of the old code for how I processed that data incase there were questions on it in future, until that UK wide dataset can be superseeded. I did not do this well, it would seem - apologies!!

Also, the conflict mentioned above was to deal with the version of data used for LCAT and then subsequently for the next interim data. 

However, with the exception of 'R/misc/Data_Processing_to_df.R` on the LCAT branch, I don't think we need any of these  files anymore - if you agree I will close this PR therefore and just open a PR for that single file, moved to the LCAT folder?

**Pull request closed without merging**
